<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/person.proto

namespace GPBMetadata\Model;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
€
model/person.protomodel"/
Person

first_name (	
	last_name (	B*
com.demo.api.modelZgo-backend/api/modelbproto3'
        , true);

        static::$is_initialized = true;
    }
}

