<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: service/hello.proto

namespace Service;

use Spiral\RoadRunner\GRPC;

interface HelloServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "service.HelloService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Model\Person $in
    * @return GreetResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Greet(GRPC\ContextInterface $ctx, \Model\Person $in): GreetResponse;
}
