<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/hello.proto

namespace GPBMetadata\Service;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Model\Person::initOnce();
        $pool->internalAddGeneratedFile(
            '
¹
service/hello.protoservice"!
GreetResponse
response (	2>
HelloService.
Greet.model.Person.service.GreetResponseB.
com.demo.api.serviceZgo-backend/api/servicebproto3'
        , true);

        static::$is_initialized = true;
    }
}

